---
title: "Text Input"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<br>

```{r, echo=FALSE}

shinyApp(

  ui = fluidPage(
    
    textInput("text", label = h3("Text Input"), value = "Enter text..."),
    
    hr(),
    
    fluidRow(column(12, verbatimTextOutput("value")))
    
  ),
  
  server = function(input, output) {
    
    output$value <- renderPrint({ input$text })
    
  },

  options = list(height = 350, display.mode = "showcase")
)
```

## Text Input {.tabset}

Create a text field to enter text in. The widget will pass the text displayed to the server as a character string.

**Function**

```{r eval=F, echo=T}
textInput(inputId, label, value = "")
```

**Arguments**

<span style="color: red">inputId</span> The name to use to look up the value of the widget (as a character string)

<span style="color: red">label</span> A label to display above the text field

<span style="color: red">value</span> The initial text to display in the box, if any

<br>

### ui.R
```{r, eval=F, echo=T}

fluidPage(
  
  textInput("text", label = h3("Text Input"), value = "Enter text..."),
  
  hr(),
  
  fluidRow(column(12, verbatimTextOutput("value")))
  
)
  
```
### server.R
```{r, eval=F, echo=T}

function(input, output) {

  output$value <- renderPrint({ input$text })
  
}
```
### app.R
```{r, eval=F, echo=T}

ui = fluidPage(
    
  textInput("text", label = h3("Text Input"), value = "Enter text..."),
  
  hr(),
  
  fluidRow(column(12, verbatimTextOutput("value")))
      
)

server = function(input, output) {

  output$value <- renderPrint({ input$text })

}

# Run the application 
shinyApp(ui = ui, server = server)

```
